### ISSUE TITLE
Add expand/collapse option

### ISSUE THREAD

**Issue by marjan-georgiev** [swimlane/ngx-graph#1]
Think about whether this should be built into the component, because it is also possible to implement it outside of it.

**Comment by ericsvendsen** [comment]
I'm trying to implement this outside the component and am running into trouble because nodes and links don't support two-way binding. Basically I'm updating properties on each node and link object to change visibility, but nothing happens because the UI never gets notified of the changes. Or am I going about this the wrong way?

**Comment by kenisteward** [comment]
@ericsvendsen don't know if you figured this out yet but make sure you use immutable data

e.g.
don't do
```
nodes.push(newNodeData);
```

do
```
nodes = [...nodes, newNodeData]
```

same for links.  this will make sure that the component updates with the OnPush strategy.

**Comment by assafsun** [comment]
We can test the compound option inside dagre graph.

**Comment by assafsun** [comment]
@marjan-georgiev ,Can I close this issue?
I think the expand collapse should come from the user aspect because ngx-graph is not handling the UI so different questions such as how to trigger the expand\collapse raise

**Comment by assafsun** [comment]
@marjan-georgiev Closing this one, let me know if you want to open it.
