### ISSUE TITLE
Two or more links are getting merged when creating cyclic graph

### ISSUE THREAD

**Issue by tom-riddle** [swimlane/ngx-graph#119]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If there is a link from
A to B 
and 
B to A,
on dragging any of the two nodes, the two links are getting merged.

**Expected behavior**
Separate links should not get merged

* **ngx-graph version:** x.x.x
5.1.0

* **Angular version:** x.x.x
6

**Comment by assafsun** [comment]
@marjan-georgiev is this issue related to the line change when dragging which suppose to be fixed on version 6?

**Comment by marjan-georgiev** [comment]
I see the issue. I believe this is a side effect of the dagre layout. Need to look into it more.

**Comment by assafsun** [comment]
Is it looks good before the dragging?

**Comment by assafsun** [comment]
The problem here is that ngx-graph version 5 is not calling the dagre layout again to understand the points selections but set a new points between source and target.
On version 6, I think this should not happen because the graph will call update edge. 

Closing this for now. @tom-riddle, if needed, I will open it.
Thanks.
