### ISSUE TITLE
Best Practices for extending GraphComponent

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#126]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If I extend GraphComponent and use same template, I get error for not able to resolve 'graph' variable on browser.

**Expected behavior**
I'm expecting that we should be able to extend the component along with using the template.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
We want to carry out few additions like buttons for zoom in/out on template.

**Please tell us about your environment:**

* **ngx-graph version:** x.x.x

Latest

* **Angular version:** x.x.x

6.1.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
I would recommend using the public API of the component rather than extending it, since the internals are likely to change and may cause breaking changes. You can add additional UI on top of the graph component and interact with the zoom through the component's events, you shouldn't need to extend it to do that.
