### ISSUE TITLE
problem with angular drawing links

### ISSUE THREAD

**Issue by mikeVaz0vsky** [swimlane/ngx-graph#158]
Hello, thank you for your work! I am using your library and am faced with the connection drawing gap. As you can see in the image below, I use "curve = shape.curveStep". I need the angular connections between the nodes, but curveStepAfter, curveStepBefore, curveStep do not help. I now that we tell "Please do not submit support request here" but i ned help :) Can you help me please?

This problem
![1](https://user-images.githubusercontent.com/18570923/51997742-5df66a00-24c8-11e9-8e35-42e6b3e0d964.png)

I want two types links. "shape.curveStepAfter, shape.curveStepBefore, shape.curveStep" don't help me.
![2](https://user-images.githubusercontent.com/18570923/51998020-f260cc80-24c8-11e9-9995-e980c5c22921.png)
![3](https://user-images.githubusercontent.com/18570923/51998019-f260cc80-24c8-11e9-9cf4-ee5e47a92030.png)

Thx!

**Comment by assafsun** [comment]
HI,

1. ngx-graph  gives a set of lines that were published from D3.

2. You can implement your own line if needed and passed it to the curve input.
I'm trying it now myself in my daily work.

3. The second image seems like you want a curved step after. I'm also working on this kind on this line type so I will share an information once I will have it.

4, The third image can be achieved by using a step after in dagre only nodes layout.
This will be  avaiabile in ngx-graph version 6 or you can download the master branch for local use.

I'm closing this issue, hope that this information helps, you can start undertand how D3 lines works in order to create your custom line because it will be required - it's not supported by default.
I will try to share as much information as I can and improve the code in case I will have some progress..
