### ISSUE TITLE
Creating New node between  existing 2 nodes 

### ISSUE THREAD

**Issue by maxwellfargose** [swimlane/ngx-graph#173]

**Comment by assafsun** [comment]
I'm guessing that you are referring to a create scenario from the actual graph?

**Comment by maxwellfargose** [comment]
![node](https://user-images.githubusercontent.com/26279980/54182288-1a2f5100-44c7-11e9-8237-e0a3849df2cc.png)


This is the scenario. I want to drop node between existing 2 nodes.

**Comment by CryHenry** [comment]
Could you not add an event listener to the edges template ? So that when a user drops on top of an edge, the event listener calls a function passing the edge which has the sourceid and the targetid. Then you could simply create a new node, and 2 new edges to link between your new node and the source and target of the edge you dropped on ?

**Comment by marjan-georgiev** [comment]
Yes, this can be implemented with custom logic on edge templates.
