### ISSUE TITLE
Plan for Releasing Version 6

### ISSUE THREAD

**Issue by rahul-winner** [swimlane/ngx-graph#188]
We are on version 5.4.1. We are revisiting all third parties and evaluating what all can we update to new version.

Could anyone please throw some light on when are we planning to release version 6 of ngx-graph. Version 6 got some exciting features and we are looking forward to move onto this version.

Thanks.

**Comment by marjan-georgiev** [comment]
Version 6 is in RC stage, so you can already install it.

`npm install @swimlane/ngx-graph@6.0.0-rc.6`

It is stable and we are using it in production.

The final 6.0.0 release will be released as soon as we finish the documentation. It should be very soon.

**Comment by rahul-winner** [comment]
thank you @marjan-georgiev for kind response.

could you please provide some basic idea about breaking changes when moving to 6.x version? And do we have some brief list about high level comparison?

Regards, Rahul

**Comment by marjan-georgiev** [comment]
Here's a list of the inputs in v6: https://github.com/swimlane/ngx-graph/blob/master/src/docs/main.md#inputs

You will notice a lot of them are similar. What changed is
- the format of the data (you can find the interfaces here: https://github.com/swimlane/ngx-graph/tree/master/projects/swimlane/ngx-graph/src/lib/models)
  - The main thing here is we moved the position properties into a position object, so instead of `node.x` you will need to use `node.position.x` in your templates now. Similarly, we moved the dimensions into a `dimension` property
- we are now supporting different layouts, as well as the ability to define your own custom layout
- some of the layout-specific options (line orientation) have been moved to the `layoutSettings` input, since each layout will have custom layout settings that you can pass to it
- we have also deprecated some of the inputs. They are still working, but will be removed in version 7, when it gets released.

Functionally, you should be able to have your graph look and behave in the same way when switching between 5.x and 6, after making some of the configuration changes I mentioned above. However, v6 adds so many new features on top of it.

**Comment by Laruu** [comment]
did you change something about the node.id? I got an error with v6 and dont know where it's from...

`
core.js:15714 ERROR TypeError: Cannot read property 'id' of undefined
    at index.js:116
    at Array.find (<anonymous>)
    at _loop_1 (index.js:116)
    at DagreLayout.push../node_modules/@swimlane/ngx-graph/fesm5/swimlane-ngx-graph.js.DagreLayout.run (index.js:128)
    at GraphComponent.push../node_modules/@swimlane/ngx-graph/fesm5/swimlane-ngx-graph.js.GraphComponent.draw (index.js:1559)
    at index.js:1528
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
`
