### ISSUE TITLE
Custom node height equals 0 inside material mat-tab(not the first tab)

### ISSUE THREAD

**Issue by kkseven07** [swimlane/ngx-graph#206]
**Describe the bug**
`[attr.height]="'node.dimension.height'"`
where  
`node.dimension.height =0` for any node

**Expected behavior**
Node's height should be calculated automatically. Node's should be filled with colors, but they are not because of height=0

**Steps to reproduce**
Put the ngx-graph component into material component `mat-tab`(NOT the first tab)

**Demo**
[Stackblitz](https://stackblitz.com/edit/angular-jv3eap?file=src%2Fapp%2Ftree%2Ftree.component.ts)

**ngx-graph version**
"@swimlane/ngx-graph": "^6.0.1"

Everything works if it's wrapped inside first `mat-tab`

**Comment by KingDarBoja** [comment]
Hello @kkseven07,

According to the [Angular Material Docs](https://material.angular.io/components/tabs/overview#lazy-loading), you aren't properly setting the mat-tab content because the `my-tree` component requires some DOM calculations on init, hence, you will need to wrap it inside a `ng-template` tag within `matTabContent` attribute.

Cheers!
