### ISSUE TITLE
Custom node's width isn't calculated properly

### ISSUE THREAD

**Issue by kkseven07** [swimlane/ngx-graph#213]
I added image to the custom node and set attribute `x="10"` to image and `x="30"` to text, but the node's width is calculated only for text with attribute `x="0"`
[stackblitz](https://stackblitz.com/edit/angular-jv3eap?file=src%2Fapp%2Ftree%2Ftree.component.html)

**Comment by marjan-georgiev** [comment]
This is tricky, because we can not reliably measure the actual svg element width, because we will end up in a loop if you have a padding and cause the width to increase every time the graph updates itself.

This is what we are doing with the node height, and you can see the effect I am talking about here:
https://stackblitz.com/edit/angular-m4frjb?file=src/app/tree/tree.component.html

notice that I set the rect height to be `node.dimension.height + 10`, so on every update (try resizing the browser) the node will be higher by 10 pixels.

That is why for the width, we are only measuring the width of the biggest text element of the node, so you can use that as a basis. You can set the rectangle width to be `node.dimension.width + 30`, in order to fit added picture element.

Stackblitz: https://stackblitz.com/edit/angular-yhxphs?file=src/app/tree/tree.component.html

**Comment by kkseven07** [comment]
> This is tricky, because we can not reliably measure the actual svg element width, because we will end up in a loop if you have a padding and cause the width to increase every time the graph updates itself.
> 
> This is what we are doing with the node height, and you can see the effect I am talking about here:
> https://stackblitz.com/edit/angular-m4frjb?file=src/app/tree/tree.component.html
> 
> notice that I set the rect height to be `node.dimension.height + 10`, so on every update (try resizing the browser) the node will be higher by 10 pixels.
> 
> That is why for the width, we are only measuring the width of the biggest text element of the node, so you can use that as a basis. You can set the rectangle width to be `node.dimension.width + 30`, in order to fit added picture element.
> 
> Stackblitz: https://stackblitz.com/edit/angular-yhxphs?file=src/app/tree/tree.component.html

Yeah, that is exactly what I've done. But I noticed that he arrow from the node becomes less and the start of the arrow is inside the node if I use curveStepBefore. Is there any possibility to move the start of the arrow to the same amount as we added to width?

**Comment by marjan-georgiev** [comment]
You can also predefine each node's width and height by setting `node.dimension.width` and `node.dimension.height` before passing it to the graph. The graph layout will use those values instead of measuring the node.

**Comment by kkseven07** [comment]
> You can also predefine each node's width and height by setting `node.dimension.width` and `node.dimension.height` before passing it to the graph. The graph layout will use those values instead of measuring the node.

where can I set these parameters?
