### ISSUE TITLE
Limit the number of nodes per row.

### ISSUE THREAD

**Issue by alindberg** [swimlane/ngx-graph#291]
**Is your feature request related to a problem? Please describe.**
An attribute to limit the number of nodes per row in the graph.  This request is similar to request [161](https://github.com/swimlane/ngx-graph/pull/161)

Request 161 did not make it into 6.x or 7.x (@Input() singleNodesPerLine )

**Describe the solution you'd like**
A simple attribute to limit the number of nodes on a single row

**Comment by assafsun** [comment]
It is very depended on your layout file which is use as an input to ngx-graph.
The position of the single nodes should be handle from there.

What kind of layout are you using?

**Comment by alindberg** [comment]
Perhaps a value to limit the number of nodes on a row as well as setting min/max spacing between nodes.

**Comment by assafsun** [comment]
It's a little bit problematic to add it as ngx-graph can't expect what is the graph layout

**Comment by assafsun** [comment]
I think this issue is missing some information.
what is number of nodes per row in a layout? the nodes are arranged by lines without links? 
In case a single source node is connected to two output nodes, what is a row? they will be at different location. 

I do want to share the following code that was on version 5 that helped limit the nodes per row when no links were created.
https://github.com/swimlane/ngx-graph/blob/5.x/src/graph/graph.component.ts#L438
