### ISSUE TITLE
Template parse errors : angular 5 

### ISSUE THREAD

**Issue by meriemchebaane** [swimlane/ngx-graph#66]
I used the same code in the readme : "app.component.html" but i have got a template parse error : 
<ngx-graph
  class="chart-container"
  [view]="view"
  [legend]="showLegend"
  [links]="hierarchialGraph.links"
  (legendLabelClick)="onLegendLabelClick($event)"
  [nodes]="hierarchialGraph.nodes"
  [scheme]="colorScheme"
  [orientation]="orientation"
  [curve]="curve"
  (select)="select($event)">

  <ng-template #defsTemplate>
    <svg:marker id="arrow" viewBox="0 -5 10 10" refX="8" refY="0" markerWidth="4" markerHeight="4" orient="auto">
      <svg:path d="M0,-5L10,0L0,5" class="arrow-head" />
    </svg:marker>
  </ng-template>

  <ng-template #nodeTemplate let-node>
    <svg:g class="node"
      ngx-tooltip
      [tooltipPlacement]="'top'"
      [tooltipType]="'tooltip'"
      [tooltipTitle]="node.label">
      <svg:rect [attr.width]="node.width" [attr.height]="node.height" [attr.fill]="node.options.color" />
      <svg:text alignment-baseline="central" [attr.x]="10" [attr.y]="node.height / 2">{{node.label}}</svg:text>
    </svg:g>
  </ng-template>

  <ng-template #linkTemplate let-link>
    <svg:g class="edge">
      <svg:path
        stroke-width="2"
        marker-end="url(#arrow)" >
      </svg:path>
    </svg:g>
  </ng-template>

</ngx-graph>

**Comment by isaacplmann** [comment]
What is the error?

**Comment by issamRca** [comment]
me i got this error:
Error: Template parse errors: Can't bind to 'tooltipPlacement' since it isn't a known property of ':svg:g'. (" <svg:g class="node" ngx-tooltip [ERROR ->][tooltipPlacement]="'top'" [tooltipType]="'tooltip'" [tooltipTitle]="node.label"> "): ng:///AppModule/AppComponent.html@21:6 Can't bind to 'tooltipType' since it isn't a known property of ':svg:g'. (" ngx-tooltip [tooltipPlacement]="'top'" [ERROR ->][tooltipType]="'tooltip'" [tooltipTitle]="node.label"> <svg:rect [attr.width]="node.width"): ng:///AppModule/AppComponent.html@22:6 Can't bind to 'tooltipTitle' since it isn't a known property of ':svg:g'. (" [tooltipPlacement]="'top'" [tooltipType]="'tooltip'" [ERROR ->][tooltipTitle]="node.label"> <svg:rect [attr.width]="node.width" [attr.height]="node.height" [a"): ng:///AppModule/AppComponent.html@23:6

**Comment by seshasui** [comment]
Need to import ngx-charts module to fix it.

**Comment by issamRca** [comment]
now i got that:TypeError: _co.hierarchialGraph is undefined knowing that I used the same code in the readme.
when i declare a public hierarchialGraph look like:
public hierarchialGraph = {
	links: [{
		source: 'start',
		target: '1',
		label: 'links to'
	}, {
		source: 'start',
		target: '2'
	}, ],
	nodes: [{
		id: 'start',
		label: 'start'
	}, {
		id: '1',
		label: 'Query ThreatConnect',
	}, {
		id: '2',
		label: 'Query XForce',
	}],
};
i got that:
-TypeError: scheme is undefined
-Error: Found the synthetic property @animationState
-Error: Found the synthetic property @.disabled. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

Should i import another module ?
