### ISSUE TITLE
Moving a node also fires the click event

### ISSUE THREAD

**Issue by cristianhosu** [swimlane/ngx-graph#69]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
If nodes are clickable, and you try to move a node it will also fire the click event.

**Expected behavior**
Node click and node move should be two separate events that should function independently of one another, so when I move a node it should not fire the click event.

**Comment by isaacplmann** [comment]
I think I agree with you that these events should be separate, but this would be a breaking change and someone else might be depending on it working the way it is right now.

I don't see a good path forward to implementing this without breaking people.

**Comment by cristianhosu** [comment]
Maybe add it in a new major version? Along with other features :)
I have a couple of ideas which I will write down in other tickets.

**Comment by iivok** [comment]
I also think it's really bad to mix drag and click. Also a drag threshold would be nice, so that moving the cursor a tiny while clicking bit doesn't count as drag.

Maybe there could be a new selectClick event so if someone relies on the original select event behaviour they could continue to do so. Although a new 5.x.x version won't help me, since I can't upgrade to Angular 6.

While I'm at it is there a way to listen to clicks on the graph that don't hit a node? (click) on the ngx-graph element kinda works but it also fires when clicking a node.

**Comment by assafsun** [comment]
Is this issue relevant on version 6?

**Comment by assafsun** [comment]
We will support it on version 6.

I didn't succeeded to stop the user click calling after playing with it (stop propagation on move up, move down and click inside ngx-graph). 
My thinking is that ngx-graph will have an output parameter of updating the graph state (for start, we can use only dragging and click) after each set of events. the hosting component can listen to it and take the proper action.

**Comment by assafsun** [comment]
Created a PR for fixing this problem.
https://github.com/swimlane/ngx-graph/pull/229

**Comment by assafsun** [comment]
Please use the clickHandler output from version 6
