### ISSUE TITLE
running issues in IE11: ERROR TypeError: The object does not handle the property or method "includes"

### ISSUE THREAD

**Issue by issamRca** [swimlane/ngx-graph#76]
my project runs perfectly in Chrome and firefox but when I tried to use IE11
 nothings shows up .
I un commented the following line of codes :polyfills.ts and run npm install the corresponding module.
`/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';`

then i got this error 

ERROR TypeError: The object does not handle the property or method "includes"
ERROR CONTEXT [object Object]

**Comment by assafsun** [comment]
We do have problems with IE 11 due to it's lack of support with SVG.

I'm closing this issue because on version 5.2.1, the graph is loaded but we do have a problem with the dragging. 
This issue is from April so I'm guessing some items were updated with your work so please update this issue or submit a new for any problem or if I missed something.

Thanks!
